name: Convox Promote
description: Promote a release
author: Convox
inputs:
  host:
    required: false
    default: console.convox.com
  password:
    required: false
  rack:
    required: false
  app:
    required: true
  release:
    required: true
runs:
  using: docker
  image: Dockerfile
